### ISSUE TITLE
Installation Version 0.0.1

### ISSUE THREAD

**Issue by sone** [navelpluisje/Reasonus-Native#24]

**Comment by sone** [comment]
Hi, 

I tried to test/use the new first version but I have no success.

I'm on latest WIN10 and latest Reaper and with a Faderport 8 with the latest firmware. SWS is installed.
I copied the file  reaper_ReasonusNative-x64.dll  to the user plug-in folder, disabled the FP8 midi IN/OUT in Reaper and added the Reasonus control surface - within the control surface I see no fields for MIDI IN/OUT port selection.
The FP8 is not working when in Sudio One mode and started before Reaper is started. 

BTW I've installed "https://github.com/navelpluisje/reasonus-install" to see if they depend on another - do they work together in any way?

Thank you very much.
Best regards

**Comment by navelpluisje** [comment]
Hi sone,
There is currently an issue with the windows version. I have an issue with all the dialogs not appearing.
I would suggest to remove it foro now. I'll post updates on the forum: https://forum.cockos.com/showthread.php?p=2848657#post2848657

**Comment by sone** [comment]
ok, thank you for information and good success! looking forward

**Comment by noah1234j** [comment]
Sounds like this is the same issue.

![Image](https://github.com/user-attachments/assets/95f33f46-1cf4-481b-a60e-2ca716e5c59f)

**Comment by gaabora** [comment]
Hi @navelpluisje  this is probably cmake + wdl issue.

(getting exactly same on on [this csi fork](https://github.com/gaabora/Reaper-ControlSurfaceIntegrator) after refactoring it to cmake. but on macos build it was ok)

**Comment by gaabora** [comment]
![Image](https://github.com/user-attachments/assets/c51c273f-ebfe-48df-998c-29f29703c941)
consider fixed by https://github.com/navelpluisje/Reasonus-Native/pull/25 😅 ?

**Comment by navelpluisje** [comment]
@gaabora You're a hero. Works for me as well. Still some issues, but this issue got me so demotivated.

**Comment by navelpluisje** [comment]
Thanx, I'll try to some testing this evening and hopefully will create a testable version this weekend. It might still have some issues, but most of the functionality should be working then

**Comment by navelpluisje** [comment]
@sone New version is available here: https://github.com/navelpluisje/Reasonus-Native/releases
Would you mind check if it working now? Like mentioned above there still might be issues. If you run into them, please report them.

**Comment by sone** [comment]
@navelpluisje yes, it is working now! it's only a first impression and I have to go through the documentation and test the functionality. would it be possible to compile reasonus native for linux, too?
